spring.application.name=orderservice

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.yaml

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true

resilience4j.circuitbreaker.instances.userservice.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userservice.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userservice.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.userservice.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.userservice.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userservice.sliding-window-size=10
resilience4j.circuitbreaker.instances.userservice.sliding-window-type=count_based
resilience4j.circuitbreaker.instances.userservice.ignore-exceptions[0]=com.innowise.orderservice.exceptions.ResourceNotFoundException
resilience4j.circuitbreaker.instances.userservice.ignore-exceptions[1]=org.springframework.security.authorization.AuthorizationDeniedException
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.payment.topic.name=${KAFKA_PAYMENT_TOPIC_NAME:payment-events}
kafka.order.topic.name=${KAFKA_ORDER_TOPIC_NAME:order-events}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.innowise.orderservice.model.events.PaymentStatusEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.group-id=1
spring.kafka.consumer.properties.spring.json.trusted.packages=com.innowise.orderservice.model.events

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.use.type.headers=false