spring.datasource.url=jdbc:postgresql://localhost:5432/orderservicedb
spring.datasource.username=root
spring.datasource.password=Rembrandt17

userservice.url=localhost:8081
userservice.path=/userservice